### ISSUE TITLE
Loop out in regtest with remote signing errors

### ISSUE THREAD

**Issue by mrtestyboy781** [lightninglabs/loop#437] opened 2021-11-17 15:59 UTC
**Expected behavior**
Doing a loop out in [regtest](https://github.com/lightninglabs/loop/tree/master/regtest) with a [remote-signing setup](https://github.com/lightningnetwork/lnd/blob/master/docs/remote-signing.md), I would expect the loop out to be able to succeed

Instead, the error is given
```
[loop] rpc error: code = Unknown desc = error deriving key on local wallet instance: address manager is watching-only
```
This is true even if --addr is passed to specify a destination address for the loop, I suppose cause it doesn't know how to construct intermediate HTLC addresses. 

Investigating further it looks like loop uses dervation path "m/1017'/1'/99'". After the first loop out attempt, it looks like this derivation path is added to the remote signing wallet, but not to the watch-only wallet. Removing .lnd/data and restarting the watch-only node and re-initating the wallet with the output of remote signers `wallet accounts list` (which node includes the m/1017'/1'/99' derivation path), I would have thought things would be happy, but instead when doing

`loop --network regtest out --amt 1000000 --fast` - the readonly node then gets error
```
[loop] rpc error: code = Unknown desc = NextAddr error: rpc error: code = Unknown desc = error deriving address on remote signing instance, got different address (bcrt1q3rnj0ja63alf9sc3w9m45assu75zsmp5ge4q3f) than on local wallet instance (bcrt1qj8z8th80kcluy8ywttwnmnxa8wwrms9lzjcx4f)
```

Listing `wallet accounts list` from  watch-only node and signing node looks pretty much identical, so I am not sure why the derivation appears different.

In general getting loop working with watch-only node seems like a chicken and egg problem, because you need to setup the watch-only/signing wallet before attempting a loop out, and then a new derivation path is added to signing wallet thats not added to readonly wallet by default, meaning you have to reset the wallet and re-import all the accounts later. `wallet accounts import` does not seem to allow specifying derivation path so importing the single new account doesn't seem to work. 

Any help debugging is appreciated. 

As a final note, it seems the output of listAccounts is now different than [watch only init](https://api.lightning.community/#lnrpc-watchonlyaccount) is expecting. The same information is there, but you have to parse out the derivation path info setup the request like initWallet wants
```
accounts = accounts.map(a => {
    return {
        purpose: parseInt(a.derivation_path.split('/')[1]),
        coin_type: parseInt(a.derivation_path.split('/')[2]),
        account: parseInt(a.derivation_path.split('/')[3]),
        xpub: a.extended_public_key,
    };
});
```

**To reproduce**
Environment setup with docker-compose with: 
bitcoind v22.0
lnd - watchonly-node
lnd - signing-node
lnd - loop server node
loopserver:latest

At launch, 
1. Mining a few blocks will make loop server init.
1. signing-node init wallet
1. have watchonly import accounts of signing node 
1. Open channel between watch-only-node and loop node with push amt. 
1. Attempt `loop out --fast --amt 1000000` (fails)
1. Kill watch-only-node and rm .lnd/data
1. Re-export accounts of signing node
1. Restart watch-only node and re-init wallet with new list of signing node accounts (including account `99`)
1. Attempt loop out again (fails again because address derivations don't match) 

**System information**

lnd :  v0.14.0-beta.rc2
loopserver : latest docker image

**Comment by guggero** [comment] 2021-11-18 08:39
Thank you for the report. I think this isn't a loop problem, really. But a problem with the remote signing.

Can you be more specific about the failure in step 5? Why does it fail there?

The problem that leads to the error in step 9 is that you `rm -rf` the `.lnd/data` of the watch-only node but not of the signer. That de-synchronizes the wallet state, as the watch-only will think it's at address 0 while the signer thinks it's at address 1.
This is because the `loop out` command will generate a new address. But because no funds are sent to that address (since the loop fails), it is not recognized when the wallet is re-initialized. So the wallet thinks it's at address 0 again.

Can you try either not scrapping the `watch-only` wallet **or** also scrapping the signing node?

We are aware that this is very limiting. And we're planning on making the remote signing way easier in the next release (goal is: not even a chain backend is needed in the signing node and no address synchronization is required anymore).

**Comment by mrtestyboy781** [comment] 2021-11-19 13:07
Thank you for your response. The initial error in step 5 is 
```
[loop] rpc error: code = Unknown desc = error deriving key on local wallet instance: address manager is watching-only
```
Because the watch-only wallet doesn't know how to generate an address the signing wallet does (it doesn't have the new  m/1017'/1'/99' path imported yet). 

The problem is then, that I can't import `"m/1017'/1'/99'"` xpub from the signer - it seems if you do `wallet accounts import` it automatically chooses a `'m/84'/...` path for the key. I can't seem to specify a custom derivation path unless im misunderstanding the command options (or the problem in general). 

I am guessing if I could import the loop xpub to watch-only node correctly, then the watch-only wallet could function without having to do any wallet resets?

**Comment by guggero** [comment] 2021-11-22 11:39
Ah, I see. The problem is indeed that the special key family `99` that is used by Loop isn't created on the signer instance by default. We only create the internal accounts and not those that are used by Loop and Pool. That's just something we forgot about. And we'll make it way easier to set up a remote signing instance with one of the next minor releases (hopefully 0.14.1 and not 0.15): https://github.com/lightningnetwork/lnd/pull/6006

In the meantime, can you try if everything works as expected if you patch your lnd (the remote signing one) and replace the line
https://github.com/lightningnetwork/lnd/blob/master/lnwallet/btcwallet/btcwallet.go#L327
with:

```
for keyFam := uint32(0); keyFam < 255; keyFam++ {
```

**Comment by mrtestyboy781** [comment] 2021-11-30 14:49
Thank you @guggero - that fix works for me. Feel free to close the ticket or keep it open until the real fix is complete

**Comment by guggero** [comment] 2021-11-30 14:57
Thank you for testing and confirming the fix. This will be properly solved by https://github.com/lightningnetwork/lnd/pull/6006.
I linked this issue in the PR so it should be auto-closed once the PR is merged.

**Closed** 2022-01-08 01:37 UTC
