### ISSUE TITLE
[loop] rpc error: code = Unknown desc = cannot initiate swap: no_route

### ISSUE THREAD

**Issue by jomagalo** [lightninglabs/loop#689] opened 2024-01-21 12:37 UTC
I have the bitcoin, lnd and loop nodes installed on the local network and I can't find a way to swap. I always get the same error:

`loop --network=testnet out --channel 2830637710137425922 --amt 250000`

[loop] rpc error: code = Unknown desc = cannot initiate swap: no_route

The indicated channel is 1,000,000sat, it is open and working correctly. The ln node account has a balance of 500,000sat

Installed versions:
Bitcoin Core 23
ln v0.17.2-beta
loop 0.26.6-beta commit=

The scenario that causes the error is the following:
One of the computers on the local network uses electrum to open a private channel and send liquidity to the node that is installed on another computer on the same local network, until then everything works fine. I suppose we will have to configure something specific so that it can work from the local network.

`lncli --network=testnet listchannels`
{
    "channels": [
        {
            "active": true,
            "remote_pubkey": "021151f8ff281ab2f1510eeb212a643f093348ca337307751b1d64cf1a0dbdcc36",
            "channel_point": "879708bda02f25be276485711e0a45563d0e55074738e58ab05114ae654896d9:2",
            "chan_id": "2830637710137425922",
            "capacity": "1000000",
            "local_balance": "500000",
            "remote_balance": "499817",
            "commit_fee": "183",
            "commit_weight": "724",
            "fee_per_kw": "253",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "500000",
            "num_updates": "7",
            "pending_htlcs": [],
            "csv_delay": 1008,
            "private": true,
            "initiator": false,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "10000",
            "remote_chan_reserve_sat": "10000",
            "static_remote_key": true,
            "commitment_type": "STATIC_REMOTE_KEY",
            "lifetime": "9535",
            "uptime": "8457",
            "close_address": "",
            "push_amount_sat": "0",
            "thaw_height": 0,
            "local_constraints": {
                "csv_delay": 1008,
                "chan_reserve_sat": "10000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "1000000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 30
            },
            "remote_constraints": {
                "csv_delay": 144,
                "chan_reserve_sat": "10000",
                "dust_limit_sat": "546",
                "max_pending_amt_msat": "990000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "alias_scids": [],
            "zero_conf": false,
            "zero_conf_confirmed_scid": "0",
            "peer_alias": "unable to lookup peer alias: alias for node not found",
            "peer_scid_alias": "0",
            "memo": ""
        }
    ]
}

`loop --network=testnet getparams`

{
    "rules":  [
        {
            "channel_id":  "2830637710137425922",
            "swap_type":  "LOOP_OUT",
            "pubkey":  "",
            "type":  "THRESHOLD",
            "incoming_threshold":  0,
            "outgoing_threshold":  0
        }
    ],
    "fee_ppm":  "20000",
    "sweep_fee_rate_sat_per_vbyte":  "0",
    "max_swap_fee_ppm":  "0",
    "max_routing_fee_ppm":  "0",
    "max_prepay_routing_fee_ppm":  "0",
    "max_prepay_sat":  "0",
    "max_miner_fee_sat":  "0",
    "sweep_conf_target":  100,
    "failure_backoff_sec":  "86400",
    "autoloop":  true,
    "autoloop_budget_sat":  "335544",
    "autoloop_budget_start_sec":  "0",
    "auto_max_in_flight":  "1",
    "min_swap_amount":  "0",
    "max_swap_amount":  "0",
    "htlc_conf_target":  6,
    "autoloop_dest_address":  "",
    "autoloop_budget_refresh_period_sec":  "604800",
    "autoloop_budget_last_refresh":  "1705832455",
    "easy_autoloop":  true,
    "easy_autoloop_local_target_sat":  "1000000",
    "account":  "",
    "account_addr_type":  "ADDRESS_TYPE_UNKNOWN"
}

`loop --network=testnet suggestswaps`

{
    "loop_out":  [],
    "loop_in":  [],
    "disqualified":  [
        {
            "channel_id":  "2830637710137425922",
            "pubkey":  "",
            "reason":  "AUTO_REASON_LIQUIDITY_OK"
        }
    ]
}

**Looped logs**

2024-01-21 14:53:25.813 [INF] LOOPD: Loop out request received
2024-01-21 14:53:25.827 [INF] LOOP: LoopOut 0.00250000 BTC to tb1qjqurempr32yx6nwfr2zhfaxqxmakukmm4pjlur (channels: 2830637710137425922)
2024-01-21 14:53:26.052 [INF] LOOP: Initiating swap request at height 2574616: amt=0.00250000 BTC, expiry=2574716
2024-01-21 14:53:26.270 [INF] LSAT: Payment of LSAT token is required, resuming/tracking previous payment from pending LSAT token
2024-01-21 14:53:26.272 [INF] LSAT: Retrying payment of LSAT token invoice
2024-01-21 14:53:26.326 [WRN] LNDC: Payment b8fe3207be5224506c40315da10e071e7c3999e73f104e335b40a1e2fb923dd9 failed: no_route
2024-01-21 14:53:26.327 [ERR] LOOPD: LoopOut: rpc error: code = Unknown desc = cannot initiate swap: no_route

**Comment by jomagalo** [comment] 2024-01-21 12:40
> I have the bitcoin, lnd and loop nodes installed on the local network and I can't find a way to swap. I always get the same error:
> 
> `loop --network=testnet out --channel 2830637710137425922 --amt 250000`
> 
> [loop] rpc error: code = Unknown desc = cannot initiate swap: no_route
> 
> The indicated channel is 1,000,000sat, it is open and working correctly. The ln node account has a balance of 500,000sat

**Installed versions:**
Bitcoin Core 23
ln v0.17.2-beta
loop 0.26.6-beta commit=

**Comment by alexbosworth** [comment] 2024-01-21 15:36
Maybe you are not connected to the network?

**Comment by jomagalo** [comment] 2024-01-21 17:29
The scenario that causes the error is the following:
One of the computers on the local network uses electrum to open a channel and send liquidity to the node that is installed on another computer on the same local network, until then everything works fine. I suppose we will have to configure something specific so that it can work from the local network.

**Comment by alexbosworth** [comment] 2024-01-21 17:30
Loop works over the public global network so it needs a channel connection to that in order to Loop Out

**Comment by jomagalo** [comment] 2024-01-21 17:40
If you look at the loopd logs, this appears:

`Payment of LSAT token is required, resuming/tracking previous payment from pending LSAT token`

**Comment by hieblmi** [comment] 2024-01-22 10:02
Do you have a public channel to the network on the node from where you are trying to loop out from?

**Comment by jomagalo** [comment] 2024-01-23 10:37
I have changed the scenario by creating a public channel 1M sat, sending 500,000sat through ln and trying to loop and it still gives me a no route error.

I point out that I have not put any type of rule in loopd, I run it in testnet mode only.

**Comment by hieblmi** [comment] 2024-01-23 11:35
I see that the channel connects nodes that seem to be isolated from the rest of the network? https://mempool.space/testnet/lightning/channel/2831682246249021441

Looping does only work if the loop server finds a route through the public network to your node you are trying to loop out from.
So maybe try connecting to a bigger well connected node.

**Comment by hieblmi** [comment] 2024-02-05 20:09
Closing issue as root cause seems to be identified. Please reopen if needed.

**Closed by hieblmi** 2024-02-05 20:09 UTC
