### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by grunch** [lightninglabs/loop#42] opened 2019-04-13 17:29 UTC
I'm working with a testnet node, loopd runs perfect but just for few minutes, after a while I just started to get this error on any rpc request.
```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
If I restarted loopd it works fine again, but the error starts to show after a while.

I don't see anything else on the loopd output.

loopd commit e8005d095a3dfd79269054bb9a6569b997eafe42
lncli version 0.6.0-beta commit=v0.6-beta-rc4-7-gc0141a7bc1a9e6966d1eb273e0df527236cf44ad
Bitcoin Core RPC client version v0.17.1

**Comment by Roasbeef** [comment] 2019-04-17 00:12
So you get this error when running the `loop` CLI command? 

Steps to reproduce seem to be: 
  1. Run `loopd`
  2. Wait a period of time
  3. Try to issue a command, and it shows that error


?

**Comment by grunch** [comment] 2019-04-17 14:20
Yes I get the error when running the `loop` command, this is only happening to me on testnet, at least never saw it on mainnet, I'm working on testnet for a week and it's happening all the time:
```
$ loop terms
Loop Out
--------
rpc error: code = DeadlineExceeded desc = context deadline exceeded

Loop In
------
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
This is what I see on the `loopd` terminal
```
2019-04-17 11:17:04.709 [INF] LOOPD: Monitor request received
2019-04-17 11:17:17.049 [INF] LOOPD: Loop out terms request received
2019-04-17 11:17:47.049 [ERR] LOOPD: Terms request: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2019-04-17 11:17:47.051 [INF] LOOPD: Loop in terms request received
2019-04-17 11:18:17.051 [ERR] LOOPD: Terms request: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by frennkie** [comment] 2019-09-21 20:40
Just ran into this too. Stopping loopd and starting again fixed it...

**Comment by joostjager** [comment] 2020-04-22 14:10
@grunch @frennkie is this something that still happens?

**Comment by guggero** [comment] 2020-04-22 14:15
Looks like our testnet server doesn't respond in time.

**Comment by frennkie** [comment] 2020-04-23 21:25
I believe I was running 0.2.x when I had this issue. I yesterday tested (on `verion 0.5.1-beta`) both a `loop in` and a `loop out` **successfully**.

**Comment by joostjager** [comment] 2020-04-24 06:08
Ok, will close this issue for now then. Can be reopened if it shows up again. We can then also investigate with a more recent version.

**Closed by joostjager** 2020-04-24 06:08 UTC
