### ISSUE TITLE
Loop out tuck transaction

### ISSUE THREAD

**Issue by Tedor4** [lightninglabs/loop#573] opened 2023-04-25 13:10 UTC
Hello,

I've been trying to use lightning network recently and wanted to rebalance my channel with a loop out transaction. I'm really a beginner with little IT skills.

This is exactly what I believed happen :

- I did a loop out transaction to bring BTC back to my on-chain address using Lightning Terminal on my Umbrel node.
- I thought the funds did reach my on-chain wallets as they appeared there.
- A few days later my node went off-line and I lost my LND channels as they had been force closed by the counterparty.
- I turned my node back on again and synchronized the BTC blockchain etc and opened new LND channels.
- I wanted to send funds to those new channels but noted that part of my funds were stuck due to a pending transaction.
- I noticed that the relevant transaction related to my previous Loop Out was pending in the MemPool due to low fees.
- I did not know what to do and decided to wait until the MemPool drops itself the transaction.
- This happen but the funds did not return to my...I dont' know maybe LND channel? I did not thought that this was probably impossible.
- Now it seems that my transaction is pending forever and I don't know what to do.

This is the way I understand the situation but my misunderstanding is probably polluting the explanation. 

Could you please provide me with some advice to recover my funds and make them usable again?

Thank you very much for your help which is very much appreciated.

PS. This is the transaction: 46087e7a28056dc4e134007426b48dc4ca8d7898439644da33084628a0c517d0

**Comment by GeorgeTsagk** [comment] 2023-04-25 13:14
> 46087e7a28056dc4e134007426b48dc4ca8d7898439644da33084628a0c517d0

This transaction, which brings the "Loop Out" funds back to you, seems to be already confirmed. Your funds should appear in your wallet.

What tool are you using to check your wallet coins? (e.g UI / CLI ?)

**Comment by Tedor4** [comment] 2023-04-25 13:24
Thanks for your prompt reply. When I use Ride The Lightning for example, I see in the On-chain Balance section an Unconfirmed amount of  2,489,923 SAT. Maybe there is something I don't understand. I assume it is coming from what I explain but maybe not. Thanks again.

**Comment by GeorgeTsagk** [comment] 2023-04-27 15:04
a) Are you able to provide custom arguments to LND and restart it at will through Umbrel?
b) Are you able to run `lncli` commands through Umbrel? (lncli is the command line tool we use to access LND)

**Comment by Tedor4** [comment] 2023-04-29 08:43
Hello, sorry no, my command line knowledge is close to nil. I'm just a regular user trying to adopt Bitcoin and LND and use it in my daily life with my own node. Is there a way to make the recovery of my coins easier?

**Comment by saubyk** [comment] 2023-05-02 23:27
> The on-chain balance that is unconfirmed for several weeks now is the sum of 2 transactions based on my transactions history as it appears in Ride the Lightning:
> 
> 46087e7a28056dc4e134007426b48dc4ca8d7898439644da33084628a0c517d0 and 46fecd345b06242984e57e0cc437cf3178cfa7a581a9d84e59dc7c742e6aa6e3

Hi @Tedor4 can you please post a screenshot of how the transactions are appearing in RTL?

**Comment by saubyk** [comment] 2023-05-02 23:28
Also `46fecd345b06242984e57e0cc437cf3178cfa7a581a9d84e59dc7c742e6aa6e3` does not appear to be a valid transaction id

**Comment by Tedor4** [comment] 2023-05-11 12:53
Hello Saubyk,

Please find attached the screenshot from RTL.

Thanks again for your help. :-)
![RTL_unconfirmed](https://github.com/lightninglabs/loop/assets/131778024/9f59678e-d394-41e1-954d-b7a248379208)

**Comment by Tedor4** [comment] 2023-05-17 16:48
Hello, is the information I have provided useful? Thanks again for your help. ;-)

**Comment by saubyk** [comment] 2023-05-26 01:45
Hi @Tedor4 from the screenshot you posted, all your transactions appear to be confirmed, except one for 136 sats, which is a dust amount anyway. So I am unclear what the issue is.

**Comment by Tedor4** [comment] 2023-06-30 06:08
Hi Saubyk, thank you for having a look at it. As you can see on the screenshot, top left, there is an unconfirmed balance of 2.489.923 sats. I am not able to spend this balance or use it to feed my LN channel. I don't understand why. Thank you very much.

**Comment by saubyk** [comment] 2023-06-30 17:10
Hi @Tedor4 this is a bit confusing, as from the transaction list on the screenshot, I don't see any transaction which is unconfirmed other than the 136 sats one. Can you please post a screenshot of the UTXO tab?

**Comment by hieblmi** [comment] 2023-07-24 09:36
@Tedor4, is this still there still an issue for you or do all balances now show up as confirmed? If not could you provide the UTXO tab that @saubyk asked for? If all looks good please close this issue. Thank you.

**Comment by hieblmi** [comment] 2023-12-22 09:57
Closing due to inactivity. Feel free to reopen if needed.

**Closed by hieblmi** 2023-12-22 09:57 UTC
